// 문장분석 학습 데이터 - Points 45-51 (관계대명사/관계부사)
// 예문은 문법 패턴 교육을 위해 새로 작성된 오리지널 문장입니다.

const LABELS = {
  S:   { ko:'주어',       color:'#2563EB', bg:'#DBEAFE' },
  V:   { ko:'동사',       color:'#DC2626', bg:'#FEE2E2' },
  O:   { ko:'목적어',     color:'#059669', bg:'#D1FAE5' },
  SC:  { ko:'주격보어',   color:'#D97706', bg:'#FEF3C7' },
  IO:  { ko:'간접목적어', color:'#7C3AED', bg:'#EDE9FE' },
  DO:  { ko:'직접목적어', color:'#4F46E5', bg:'#E0E7FF' },
  OC:  { ko:'목적격보어', color:'#DB2777', bg:'#FCE7F3' },
  M:   { ko:'수식어',     color:'#6B7280', bg:'#F3F4F6' },
  ANC: { ko:'선행사',     color:'#B45309', bg:'#FEF3C7', bold:true },
  REL: { ko:'관계사',     color:'#6D28D9', bg:'#EDE9FE', bold:true },
  RCS: { ko:"관계절 S'",  color:'#1D4ED8', bg:'#DBEAFE' },
  RCV: { ko:"관계절 V'",  color:'#B91C1C', bg:'#FEE2E2' },
  RCO: { ko:"관계절 O'",  color:'#047857', bg:'#D1FAE5' },
  RCM: { ko:"관계절 M'",  color:'#4B5563', bg:'#F9FAFB' },
};

const POINTS = [
  {
    id: 45,
    title: '주격 관계대명사',
    formula: '명사 + who/which/that + 동사',
    note: '관계대명사가 관계사절 안에서 주어(S\') 역할',
    antecedentTable: [
      { type:'사람', pronoun:'who / that' },
      { type:'사물·동물', pronoun:'which / that' },
    ],
    examples: [
      {
        id:'ex451',
        tokens:[
          {t:'She',     r:['S']},
          {t:'is',      r:['V']},
          {t:'the chef',r:['SC','ANC']},
          {t:'/',       r:['DIV']},
          {t:'who',     r:['REL','RCS']},
          {t:'makes',   r:['RCV']},
          {t:'all our food', r:['RCO']},
          {t:'.',       r:['PUNC']},
        ],
        translation:'그녀는 우리 음식을 모두 만드는 요리사이다.',
        antecedent:'the chef', relWord:'who', antType:'사람',
      },
      {
        id:'ex452',
        tokens:[
          {t:'I',       r:['S']},
          {t:'have',    r:['V']},
          {t:'a dog',   r:['O','ANC']},
          {t:'/',       r:['DIV']},
          {t:'which',   r:['REL','RCS']},
          {t:'loves',   r:['RCV']},
          {t:'playing outside', r:['RCO']},
          {t:'.',       r:['PUNC']},
        ],
        translation:'나는 밖에서 노는 것을 좋아하는 개를 키운다.',
        antecedent:'a dog', relWord:'which', antType:'사물·동물',
      },
    ],
    practice: [
      {
        id:'pr451',
        tokens:[
          {t:'The woman',    r:['S','ANC']},
          {t:'who',          r:['REL','RCS']},
          {t:'called me',    r:['RCV','RCO']},
          {t:'was',          r:['V']},
          {t:'my teacher',   r:['SC']},
          {t:'.',            r:['PUNC']},
        ],
        translation:'나에게 전화한 여자는 내 선생님이었다.',
      },
      {
        id:'pr452',
        tokens:[
          {t:'I',        r:['S']},
          {t:'found',    r:['V']},
          {t:'the key',  r:['O','ANC']},
          {t:'that',     r:['REL','RCS']},
          {t:'opens',    r:['RCV']},
          {t:'this door',r:['RCO']},
          {t:'.',        r:['PUNC']},
        ],
        translation:'나는 이 문을 여는 열쇠를 찾았다.',
      },
      {
        id:'pr453',
        tokens:[
          {t:'She',      r:['S']},
          {t:'is',       r:['V']},
          {t:'a singer', r:['SC','ANC']},
          {t:'who',      r:['REL','RCS']},
          {t:'wrote',    r:['RCV']},
          {t:'this song',r:['RCO']},
          {t:'.',        r:['PUNC']},
        ],
        translation:'그녀는 이 노래를 쓴 가수이다.',
      },
    ],
    quiz: [
      { id:'qz451', sentence:'I know the boy ___ won the race.', choices:['who','which','whose','whom'], answer:0, hint:'선행사가 사람(the boy)이고 관계사가 절의 주어 역할' },
      { id:'qz452', sentence:'She bought a bag ___ was very cheap.', choices:['who','which','whose','what'], answer:1, hint:'선행사가 사물(a bag)이고 관계사가 절의 주어 역할' },
    ],
  },

  {
    id: 46,
    title: '목적격 관계대명사',
    formula: '명사 + whom/which/that + 주어 + 동사',
    note: '관계대명사가 관계사절 안에서 목적어(O\') 역할 - 생략 가능',
    antecedentTable: [
      { type:'사람', pronoun:'whom / who / that' },
      { type:'사물·동물', pronoun:'which / that' },
    ],
    examples: [
      {
        id:'ex461',
        tokens:[
          {t:'He',        r:['S']},
          {t:'is',        r:['V']},
          {t:'the actor', r:['SC','ANC']},
          {t:'/',         r:['DIV']},
          {t:'whom',      r:['REL','RCO']},
          {t:'I',         r:['RCS']},
          {t:'admire',    r:['RCV']},
          {t:'most',      r:['RCM']},
          {t:'.',         r:['PUNC']},
        ],
        translation:'그는 내가 가장 존경하는 배우이다.',
        antecedent:'the actor', relWord:'whom', antType:'사람',
      },
      {
        id:'ex462',
        tokens:[
          {t:'This',       r:['S']},
          {t:'is',         r:['V']},
          {t:'the book',   r:['SC','ANC']},
          {t:'/',          r:['DIV']},
          {t:'which',      r:['REL','RCO']},
          {t:'she',        r:['RCS']},
          {t:'recommended',r:['RCV']},
          {t:'.',          r:['PUNC']},
        ],
        translation:'이것은 그녀가 추천한 책이다.',
        antecedent:'the book', relWord:'which', antType:'사물·동물',
      },
    ],
    practice: [
      {
        id:'pr461',
        tokens:[
          {t:'She',        r:['S']},
          {t:'is',         r:['V']},
          {t:'the friend', r:['SC','ANC']},
          {t:'whom',       r:['REL','RCO']},
          {t:'I',          r:['RCS']},
          {t:'trust',      r:['RCV']},
          {t:'most',       r:['RCM']},
          {t:'.',          r:['PUNC']},
        ],
        translation:'그녀는 내가 가장 믿는 친구이다.',
      },
      {
        id:'pr462',
        tokens:[
          {t:'I',          r:['S']},
          {t:'liked',      r:['V']},
          {t:'the movie',  r:['O','ANC']},
          {t:'that',       r:['REL','RCO']},
          {t:'you',        r:['RCS']},
          {t:'suggested',  r:['RCV']},
          {t:'.',          r:['PUNC']},
        ],
        translation:'나는 네가 제안한 영화가 마음에 들었다.',
      },
    ],
    quiz: [
      { id:'qz461', sentence:'The girl ___ I like moved to another city.', choices:['who','which','whose','what'], answer:0, hint:'선행사 the girl이 사람이고 관계사는 절의 목적어 역할 (who/whom 가능)' },
      { id:'qz462', sentence:'The report ___ he wrote was excellent.', choices:['who','which','whose','what'], answer:1, hint:'선행사 the report가 사물이고 관계사는 절의 목적어 역할' },
    ],
  },

  {
    id: 47,
    title: '전치사 + 관계대명사',
    formula: '명사 + 전치사 + whom/which + 주어 + 동사',
    note: '전치사를 관계사 앞에 쓸 때는 that·who 불가 / 전치사를 절 뒤에 쓸 때는 모두 가능',
    antecedentTable: [],
    examples: [
      {
        id:'ex471',
        tokens:[
          {t:'He',           r:['S']},
          {t:'is',           r:['V']},
          {t:'the friend',   r:['SC','ANC']},
          {t:'/',            r:['DIV']},
          {t:'with whom',    r:['REL']},
          {t:'I',            r:['RCS']},
          {t:'studied',      r:['RCV']},
          {t:'.',            r:['PUNC']},
        ],
        translation:'그는 내가 함께 공부한 친구이다.',
        antecedent:'the friend', relWord:'with whom', antType:'사람',
        note:'= the friend whom I studied with',
      },
      {
        id:'ex472',
        tokens:[
          {t:'This',         r:['S']},
          {t:'is',           r:['V']},
          {t:'the room',     r:['SC','ANC']},
          {t:'/',            r:['DIV']},
          {t:'in which',     r:['REL']},
          {t:'we',           r:['RCS']},
          {t:'practice',     r:['RCV']},
          {t:'.',            r:['PUNC']},
        ],
        translation:'이곳은 우리가 연습하는 방이다.',
        antecedent:'the room', relWord:'in which', antType:'사물·동물',
        note:'= the room which we practice in',
      },
    ],
    practice: [
      {
        id:'pr471',
        tokens:[
          {t:'She',          r:['S']},
          {t:'is',           r:['V']},
          {t:'the person',   r:['SC','ANC']},
          {t:'for whom',     r:['REL']},
          {t:'I',            r:['RCS']},
          {t:'bought',       r:['RCV']},
          {t:'this gift',    r:['RCO']},
          {t:'.',            r:['PUNC']},
        ],
        translation:'그녀는 내가 이 선물을 산 사람이다.',
      },
    ],
    quiz: [
      { id:'qz471', sentence:'He is the man with ___ I work.', choices:['who','which','whom','whose'], answer:2, hint:'전치사(with) 바로 뒤에는 whom을 써야 합니다.' },
    ],
  },

  {
    id: 48,
    title: '소유격 관계대명사',
    formula: '명사 + whose + 다른 명사(+ 주어) + 동사',
    note: '선행사가 사람/사물 모두 가능 / whose = 선행사의 ~의',
    antecedentTable: [
      { type:'사람·사물 모두', pronoun:'whose' },
    ],
    examples: [
      {
        id:'ex481',
        tokens:[
          {t:'I',            r:['S']},
          {t:'know',         r:['V']},
          {t:'a girl',       r:['O','ANC']},
          {t:'/',            r:['DIV']},
          {t:'whose',        r:['REL']},
          {t:'mother',       r:['RCS']},
          {t:'is',           r:['RCV']},
          {t:'a nurse',      r:['RCO']},
          {t:'.',            r:['PUNC']},
        ],
        translation:'나는 어머니가 간호사인 여자아이를 안다.',
        antecedent:'a girl', relWord:'whose', antType:'사람',
      },
      {
        id:'ex482',
        tokens:[
          {t:'We',           r:['S']},
          {t:'found',        r:['V']},
          {t:'a cat',        r:['O','ANC']},
          {t:'/',            r:['DIV']},
          {t:'whose',        r:['REL']},
          {t:'leg',          r:['RCS']},
          {t:'was',          r:['RCV']},
          {t:'hurt',         r:['RCO']},
          {t:'.',            r:['PUNC']},
        ],
        translation:'우리는 다리를 다친 고양이를 발견했다.',
        antecedent:'a cat', relWord:'whose', antType:'사물·동물',
      },
    ],
    practice: [
      {
        id:'pr481',
        tokens:[
          {t:'The man',      r:['S','ANC']},
          {t:'whose',        r:['REL']},
          {t:'car',          r:['RCS']},
          {t:'broke down',   r:['RCV']},
          {t:'called',       r:['V']},
          {t:'a mechanic',   r:['O']},
          {t:'.',            r:['PUNC']},
        ],
        translation:'차가 고장 난 남자는 정비사를 불렀다.',
      },
      {
        id:'pr482',
        tokens:[
          {t:'She',          r:['S']},
          {t:'is',           r:['V']},
          {t:'the writer',   r:['SC','ANC']},
          {t:'whose',        r:['REL']},
          {t:'novel',        r:['RCS']},
          {t:'I',            r:['RCS']},
          {t:'love',         r:['RCV']},
          {t:'.',            r:['PUNC']},
        ],
        translation:'그녀는 내가 소설을 좋아하는 작가이다.',
      },
    ],
    quiz: [
      { id:'qz481', sentence:'He is the student ___ essay won first place.', choices:['who','which','whose','whom'], answer:2, hint:'뒤에 명사(essay)가 오면 소유격 관계대명사 whose' },
    ],
  },

  {
    id: 49,
    title: '관계대명사 what',
    formula: 'what(+주어) + 동사',
    note: 'what = the thing(s) which / 선행사를 포함한 관계대명사 / 문장에서 S, O, SC 역할',
    antecedentTable: [
      { type:'선행사 포함 (= the thing which)', pronoun:'what' },
    ],
    examples: [
      {
        id:'ex491',
        tokens:[
          {t:'What',         r:['S','REL']},
          {t:'she',          r:['RCS']},
          {t:'said',         r:['RCV']},
          {t:'/',            r:['DIV']},
          {t:'was',          r:['V']},
          {t:'surprising',   r:['SC']},
          {t:'.',            r:['PUNC']},
        ],
        translation:'그녀가 말한 것은 놀라웠다.',
        relWord:'what', antType:'선행사 포함',
      },
      {
        id:'ex492',
        tokens:[
          {t:'I',            r:['S']},
          {t:'will show',    r:['V']},
          {t:'you',          r:['IO']},
          {t:'/',            r:['DIV']},
          {t:'what',         r:['REL','DO']},
          {t:'I',            r:['RCS']},
          {t:'made',         r:['RCV']},
          {t:'.',            r:['PUNC']},
        ],
        translation:'내가 만든 것을 너에게 보여줄게.',
        relWord:'what', antType:'선행사 포함',
      },
    ],
    practice: [
      {
        id:'pr491',
        tokens:[
          {t:'What',         r:['S','REL']},
          {t:'he',           r:['RCS']},
          {t:'did',          r:['RCV']},
          {t:'was',          r:['V']},
          {t:'wrong',        r:['SC']},
          {t:'.',            r:['PUNC']},
        ],
        translation:'그가 한 것은 잘못된 것이었다.',
      },
      {
        id:'pr492',
        tokens:[
          {t:'Tell',         r:['V']},
          {t:'me',           r:['IO']},
          {t:'what',         r:['REL','DO']},
          {t:'you',          r:['RCS']},
          {t:'want',         r:['RCV']},
          {t:'.',            r:['PUNC']},
        ],
        translation:'네가 원하는 것을 나에게 말해.',
      },
    ],
    quiz: [
      { id:'qz491', sentence:'___ matters most is your health.', choices:['That','Which','What','Who'], answer:2, hint:'선행사가 없고, 주어절 역할을 하므로 what' },
      { id:'qz492', sentence:'Show me ___ you can do.', choices:['that','which','what','who'], answer:2, hint:'= show me the thing which you can do → what' },
    ],
  },

  {
    id: 50,
    title: '관계부사',
    formula: '때/장소/이유/방법 + when/where/why/how + 주어 + 동사',
    note: '관계부사 = 전치사 + which / how의 선행사 the way와 함께 쓰지 않음',
    antecedentTable: [
      { type:'때 (time, day…)', pronoun:'when' },
      { type:'장소 (place…)', pronoun:'where' },
      { type:'이유 (reason)', pronoun:'why' },
      { type:'방법 (way)', pronoun:'how' },
    ],
    examples: [
      {
        id:'ex501',
        tokens:[
          {t:'I',            r:['S']},
          {t:'remember',     r:['V']},
          {t:'the day',      r:['O','ANC']},
          {t:'/',            r:['DIV']},
          {t:'when',         r:['REL']},
          {t:'we',           r:['RCS']},
          {t:'first met',    r:['RCV']},
          {t:'.',            r:['PUNC']},
        ],
        translation:'나는 우리가 처음 만난 날을 기억한다.',
        antecedent:'the day', relWord:'when', antType:'때',
      },
      {
        id:'ex502',
        tokens:[
          {t:'This',         r:['S']},
          {t:'is',           r:['V']},
          {t:'the city',     r:['SC','ANC']},
          {t:'/',            r:['DIV']},
          {t:'where',        r:['REL']},
          {t:'I',            r:['RCS']},
          {t:'was born',     r:['RCV']},
          {t:'.',            r:['PUNC']},
        ],
        translation:'이곳은 내가 태어난 도시이다.',
        antecedent:'the city', relWord:'where', antType:'장소',
      },
      {
        id:'ex503',
        tokens:[
          {t:'Tell',         r:['V']},
          {t:'me',           r:['IO']},
          {t:'the reason',   r:['DO','ANC']},
          {t:'/',            r:['DIV']},
          {t:'why',          r:['REL']},
          {t:'you',          r:['RCS']},
          {t:'were late',    r:['RCV']},
          {t:'.',            r:['PUNC']},
        ],
        translation:'네가 늦은 이유를 나에게 말해.',
        antecedent:'the reason', relWord:'why', antType:'이유',
      },
    ],
    practice: [
      {
        id:'pr501',
        tokens:[
          {t:'I',            r:['S']},
          {t:'know',         r:['V']},
          {t:'the place',    r:['O','ANC']},
          {t:'where',        r:['REL']},
          {t:'she',          r:['RCS']},
          {t:'hides',        r:['RCV']},
          {t:'her diary',    r:['RCO']},
          {t:'.',            r:['PUNC']},
        ],
        translation:'나는 그녀가 일기를 숨기는 장소를 안다.',
      },
      {
        id:'pr502',
        tokens:[
          {t:'Do you know',  r:['V']},
          {t:'the reason',   r:['O','ANC']},
          {t:'why',          r:['REL']},
          {t:'he',           r:['RCS']},
          {t:'quit',         r:['RCV']},
          {t:'the team',     r:['RCO']},
          {t:'?',            r:['PUNC']},
        ],
        translation:'그가 팀을 떠난 이유를 아니?',
      },
    ],
    quiz: [
      { id:'qz501', sentence:'That is the park ___ we used to play.', choices:['when','where','why','how'], answer:1, hint:'선행사가 장소(the park)이므로 where' },
      { id:'qz502', sentence:'I remember the time ___ we were classmates.', choices:['when','where','why','how'], answer:0, hint:'선행사가 때(the time)이므로 when' },
      { id:'qz503', sentence:'She explained the reason ___ she left early.', choices:['when','where','why','how'], answer:2, hint:'선행사가 이유(the reason)이므로 why' },
    ],
  },

  {
    id: 51,
    title: '관계대명사/관계부사의 계속적 용법',
    formula: '명사, + who/which/when/where + 주어 + 동사',
    note: '콤마(,) 뒤에 관계사 사용 / and, but으로 바꿔 해석 / that·what은 계속적 용법 불가',
    antecedentTable: [],
    examples: [
      {
        id:'ex511',
        tokens:[
          {t:'I',            r:['S']},
          {t:'visited',      r:['V']},
          {t:'Paris,',       r:['O','ANC']},
          {t:'/',            r:['DIV']},
          {t:'where',        r:['REL']},
          {t:'I',            r:['RCS']},
          {t:'met',          r:['RCV']},
          {t:'my old friend',r:['RCO']},
          {t:'.',            r:['PUNC']},
        ],
        translation:'나는 파리를 방문했는데, 거기서 옛 친구를 만났다.',
        antecedent:'Paris', relWord:'where', antType:'장소',
        note:'= I visited Paris, and there I met my old friend.',
      },
      {
        id:'ex512',
        tokens:[
          {t:'She',          r:['S']},
          {t:'has',          r:['V']},
          {t:'a sister,',    r:['O','ANC']},
          {t:'/',            r:['DIV']},
          {t:'who',          r:['REL','RCS']},
          {t:'lives',        r:['RCV']},
          {t:'in London',    r:['RCM']},
          {t:'.',            r:['PUNC']},
        ],
        translation:'그녀에게는 언니가 있는데, 런던에 산다.',
        antecedent:'a sister', relWord:'who', antType:'사람',
        note:'= She has a sister, and she lives in London.',
      },
    ],
    practice: [
      {
        id:'pr511',
        tokens:[
          {t:'He',           r:['S']},
          {t:'called',       r:['V']},
          {t:'his mom,',     r:['O','ANC']},
          {t:'who',          r:['REL','RCS']},
          {t:'was',          r:['RCV']},
          {t:'at work',      r:['RCM']},
          {t:'.',            r:['PUNC']},
        ],
        translation:'그는 어머니에게 전화했는데, 어머니는 직장에 계셨다.',
      },
    ],
    quiz: [
      { id:'qz511', sentence:'I went to the beach, ___ we had a picnic.', choices:['that','what','where','which'], answer:2, hint:'계속적 용법에서 장소 선행사 뒤에는 where (that 불가)' },
    ],
  },
];
